[colors]
[colors.primary]
background = '#232A2E'
foreground = '#F8F9E8'

[colors.normal]
black = '#58686D'
red = '#F57F82'
green = '#CBE3B3'
yellow = '#F5D098'
blue = '#B2CAED'
magenta = '#D2BDF3'
cyan = '#B3E3CA'
white = '#F8F9E8'

[colors.bright]
black = '#58686D'
red = '#F57F82'
green = '#CBE3B3'
yellow = '#F5D098'
blue = '#B2CAED'
magenta = '#D2BDF3'
cyan = '#B3E3CA'
white = '#F8F9E8'
